"""
Data collection tool -- Serper search + scrape.

Takes search queries (from taxonomy), searches the web via Serper,
scrapes the top pages, and returns collected text as an HF Dataset.

Requires: SERPER_API_KEY env var.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import aiohttp

from tools.base_tool import BaseTool
from tools.collect_data.images import collect_images

try:
    from datasets import Dataset
except Exception:  # pragma: no cover
    Dataset = None  # type: ignore[assignment]

logger = logging.getLogger(__name__)

SERPER_SEARCH_URL = "https://google.serper.dev/search"
SERPER_SCRAPE_URL = "https://scrape.serper.dev"
HTTP_TIMEOUT_S = 30.0

EXCLUDED_DOMAINS = [
    "facebook.com", "instagram.com", "youtube.com", "tiktok.com",
    "twitter.com", "x.com", "reddit.com", "pinterest.com",
    "linkedin.com", "vk.com", "ok.ru", "t.me",
    "play.google.com", "apps.apple.com",
]

_SITE_EXCLUSION_SUFFIX = " ".join(f"-site:{d}" for d in EXCLUDED_DOMAINS)


class CollectDataTool(BaseTool):
    """
    Searches the web for each query via Serper, scrapes the top pages,
    and saves the collected text as an HF Dataset on disk.

    The queries are already multilingual (generated by the taxonomy tool),
    so each query is searched exactly once without language filtering.
    """

    def execute(self, config: Dict[str, Any]) -> Dict[str, Any]:
        if not isinstance(config, dict):
            raise TypeError("CollectDataTool.execute expects config as a dict.")

        queries = (
            config.get("queries")
            or config.get("keywords")
            or config.get("seed_keywords")
        )
        if not queries or not isinstance(queries, (list, tuple)):
            raise ValueError("config['queries'] must be a non-empty list[str].")

        serper_key = os.getenv("SERPER_API_KEY")
        if not serper_key:
            raise EnvironmentError("SERPER_API_KEY is required.")
        if Dataset is None:
            raise RuntimeError("'datasets' package is required.")

        run_dir = self._resolve_run_dir(config)
        run_dir.mkdir(parents=True, exist_ok=True)

        results_per_query = config.get("google_results_per_query", 10)
        top_n = config.get("top_results", 5)
        concurrency = config.get("concurrency", 50)
        max_samples: Optional[int] = config.get("size")
        do_images: bool = bool(config.get("collect_images", False))
        image_min_width: int = int(config.get("image_min_width", 300))
        image_min_height: int = int(config.get("image_min_height", 300))
        image_context_size: int = int(config.get("image_context_size", 500))

        raw = asyncio.run(
            _search_and_scrape(
                queries=list(queries),
                serper_key=serper_key,
                results_per_query=results_per_query,
                top_n=top_n,
                concurrency=concurrency,
            )
        )

        raw_path = run_dir / "serper_raw.json"
        raw_path.write_text(json.dumps(raw, ensure_ascii=False, indent=2), encoding="utf-8")

        texts = _extract_texts(raw)
        if max_samples and max_samples > 0:
            texts = texts[:max_samples]
        if not texts:
            texts = ["(no text collected)"]

        dataset = Dataset.from_list([{"text": t} for t in texts])
        dataset_dir = run_dir / "dataset"
        dataset.save_to_disk(str(dataset_dir))

        images_meta: Dict[str, Any] = {}
        if do_images:
            scraped_urls = [
                page["url"]
                for pages in raw.values()
                for page in pages
                if page.get("url")
            ]
            images_dir = run_dir / "images"
            image_records = asyncio.run(
                collect_images(
                    scraped_urls,
                    images_dir,
                    concurrency=concurrency,
                    context_size=image_context_size,
                    min_width=image_min_width,
                    min_height=image_min_height,
                )
            )
            images_json = run_dir / "images.json"
            images_json.write_text(
                json.dumps(image_records, ensure_ascii=False, indent=2), encoding="utf-8"
            )
            images_meta = {
                "images_dir": str(images_dir),
                "images_index": str(images_json),
                "num_images": len(image_records),
            }
            logger.info("Collected %d images into %s", len(image_records), images_dir)

        return {
            "data_path": str(dataset_dir),
            "num_samples": len(dataset),
            "metadata": {
                "provider": "serper",
                "run_dir": str(run_dir),
                "raw_result_path": str(raw_path),
                "collected_at": datetime.now(timezone.utc).isoformat(),
                **images_meta,
            },
        }

    def _resolve_run_dir(self, config: Dict[str, Any]) -> Path:
        run_dir = config.get("run_dir") or config.get("out_dir")
        if run_dir:
            return Path(run_dir)
        run_id = (config.get("run_id") or "run").strip()
        return Path("data") / "raw" / run_id / "collect_data"


# ═════════════════════════════════════════════════════════════════════════════
# Async pipeline
# ═════════════════════════════════════════════════════════════════════════════

async def _search_and_scrape(
    *,
    queries: List[str],
    serper_key: str,
    results_per_query: int,
    top_n: int,
    concurrency: int,
) -> Dict[str, List[Dict[str, str]]]:
    sem = asyncio.Semaphore(concurrency)

    tasks = [
        _process_query(
            query=q,
            serper_key=serper_key,
            results_per_query=results_per_query,
            top_n=top_n,
            sem=sem,
        )
        for q in queries
    ]

    result: Dict[str, List[Dict[str, str]]] = {}
    for coro in asyncio.as_completed(tasks):
        query, pages = await coro
        result[query] = pages
        logger.info("'%s': collected %d pages", query[:60], len(pages))

    return result


async def _process_query(
    *,
    query: str,
    serper_key: str,
    results_per_query: int,
    top_n: int,
    sem: asyncio.Semaphore,
) -> tuple[str, List[Dict[str, str]]]:
    organic = await _search(serper_key, query, results_per_query, sem)
    deduped = _deduplicate(organic)[:top_n]

    scrape_tasks = [_scrape_page(serper_key, entry, sem) for entry in deduped]
    pages: List[Dict[str, str]] = []
    for coro in asyncio.as_completed(scrape_tasks):
        page = await coro
        if page:
            pages.append(page)

    return query, pages


# ─── Serper search ───────────────────────────────────────────────────────────

async def _search(
    serper_key: str,
    query: str,
    max_results: int,
    sem: asyncio.Semaphore,
) -> List[Dict]:
    async with sem:
        headers = {"X-API-KEY": serper_key, "Content-Type": "application/json"}
        full_query = f"{query} {_SITE_EXCLUSION_SUFFIX}"
        body = {"q": full_query, "num": max_results}
        timeout = aiohttp.ClientTimeout(total=HTTP_TIMEOUT_S)
        try:
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(SERPER_SEARCH_URL, json=body, headers=headers) as resp:
                    data = await resp.json()
            return data.get("organic", [])
        except Exception as e:
            logger.warning("Search failed for '%s': %s", query[:60], e)
            return []


def _is_excluded(url: str) -> bool:
    """Safety-net filter in case Google still returns an excluded domain."""
    from urllib.parse import urlparse
    try:
        host = urlparse(url).hostname or ""
    except Exception:
        return False
    host = host.lower().lstrip("www.")
    return any(host == d or host.endswith("." + d) for d in EXCLUDED_DOMAINS)


def _deduplicate(items: List[Dict]) -> List[Dict]:
    seen: set[str] = set()
    out: List[Dict] = []
    for entry in items:
        link = entry.get("link", "")
        if not link or link in seen or _is_excluded(link):
            continue
        seen.add(link)
        out.append(entry)
    return out


# ─── Serper scrape ───────────────────────────────────────────────────────────

async def _scrape_page(
    serper_key: str,
    entry: Dict,
    sem: asyncio.Semaphore,
) -> Optional[Dict[str, str]]:
    url = entry.get("link", "")
    if not url:
        return None
    async with sem:
        headers = {"X-API-KEY": serper_key, "Content-Type": "application/json"}
        timeout = aiohttp.ClientTimeout(total=HTTP_TIMEOUT_S)
        try:
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(SERPER_SCRAPE_URL, json={"url": url}, headers=headers) as resp:
                    data = await resp.json()
            text = (data.get("text") or "").strip()
            if not text:
                return None
            return {
                "url": url,
                "google_snippet": entry.get("snippet", ""),
                "full_text": text,
            }
        except Exception as e:
            logger.warning("Scrape failed for '%s': %s", url, e)
            return None


# ─── Text extraction ─────────────────────────────────────────────────────────

def _extract_texts(raw: Dict[str, List[Dict[str, str]]]) -> List[str]:
    texts: List[str] = []
    seen: set[str] = set()
    for pages in raw.values():
        for page in pages:
            full = (page.get("full_text") or "").strip()
            if full and full not in seen:
                seen.add(full)
                texts.append(full)
    return texts
